# OIDC
quarkus.oidc.client-id=quantum-health-backend
quarkus.oidc.application-type=service

# Keycloak Admin Client
quarkus.keycloak.admin-client.client-id=admin-cli
quarkus.keycloak.admin-client.username=${KEYCLOAK_ADMIN_USERNAME}
quarkus.keycloak.admin-client.password=${KEYCLOAK_ADMIN_PASSWORD}
quarkus.keycloak.admin-client.grant-type=PASSWORD

# App config
quantum-health.keycloak.realm=quantum-health

# Liquibase
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog/db.changelog-master.yaml
# Hibernate — validate schema against entities at startup
quarkus.hibernate-orm.schema-management.strategy=validate
